### PR TITLE
Add event for handle being dragged

### PR DESCRIPTION
**Pull request by samstarling**
I would find it useful for there to be an event that's fired when a segment handle is dragged. I couldn't see events being tested anywhere, so i haven't added a test. I hope I'm contributing this in a sensible way, and in the correct place! Let me know if not.

### CODE REVIEW

**Comment by oncletom** [comment]
Hello @samstarling :-)

Thanks for the contribution! What would you had the ability to listen to a `segments.handle_dragged` dragged?

IMO, we should at least provide the `segment` object as an argument, so as people could now which segment it is about, with its updated start/end properties.

Agreed it is difficult to test — ideally, it implies to see if a call to Kinetic Segment API would trigger a call to this Peaks instance event, with the expected arguments.

**Comment by un-chein-andalou** [comment]
hi @samstarling  @oncletom 
agree with oncletom, but for me I didn't need the whole segment object so I use:
```javascript
peaks.emit("segment.drag", [segment.id, segment.startTime, segment.endTime]);
```
meh,  works for me :)

**Comment by samstarling** [comment]
Hey @un-chein-andalou - that sounds like a good solution, I'll try it out!

**Comment by oncletom** [comment]
Thanks. Final implementation is `segment.dragged` with the `Segment` object. Cf. 17aa95fd9979394ace81833aad795ff146ffb8f9

**Pull request merged**
